#!/usr/bin/env bash
#
# Copyright (C) 2017-2024 Richard Mortier <mort@cantab.net>
#
# Determine if we're on the Lab network, and start the VPN if we're not. Then
# use bash `/dev/tcp` magic to setup a transparent tunnel.

cucl_local=false
while read IP; do
  if [[ $IP =~ ^128.232. ]]; then
    cucl_local=true
  fi
done < <(ip -j -4 a | jq -r '.[].addr_info | .[].local')

if [[ $cucl_local == false ]]; then
  sudo swanctl --initiate --child CUCL 2>/dev/null
fi

exec 3<>/dev/tcp/$1/$2 ; cat <&3 & cat >&3 ; kill $!
