#!/usr/bin/env bash
#
# Copyright (C) 2017-2024 Richard Mortier <mort@cantab.net>
#
# Use bash `/dev/tcp` magic to setup a transparent tunnel.

if [[ $SSH_CUCL_PROXY_DEBUG == "true" ]]; then
  set -xv
  PS4='$LINENO: '
fi

cucl_local=false
while read IP; do
  echo "=== $IP"
  if [[ $IP =~ ^128.232. ]]; then
    cucl_local=true
  fi
done < <(ip -j -4 a | jq -r '.[].addr_info | .[].local')

if [[ $cucl_local == false ]]; then
  sudo ipsec up CUCL
fi

# XXX failing with core-uutils `cat`; try `nc` instead
# cat=/run/current-system/sw/bin/cat
# exec 3<> /dev/tcp/$1/$2
# $cat <&3 &
# pid=$!
# echo "PID=$pid"
# $cat >&3
# kill $pid

nc $1 $2

if [[ $cucl_local == false ]]; then
  sudo ipsec down CUCL
fi
